### PR TITLE
Upstreaming a number of deps

### PR DESCRIPTION
**Pull request by chrisdickinson**
Hi! Thanks for your great work on `componentize-py`. I've been working to componentize an existing Python application with a number of native dependencies. I've included my progress in this PR – I'm mostly opening this now to say "hi" and compare notes!

I haven't tested these builds extensively (& combining them has a nasty tendency to run into the 100 memory limit of `wasmencoder`), but for the most part I can load them into the component sandbox demo. This PR includes the following packages (with the following "known issues"):

- `pydantic_core` (loaded, partially tested)
- `tiktoken`
    - needs missing filesystem `stat_at` capability
- `charset_normalizer` (loaded, untested)
- `regex` (loaded, untested)
- `frozenlist` (loaded, untested)
- `aiohttp`
    - I manually patch out the `#ifdef __wasm__` check in the `llhttp` vendored dep as part of `build.sh`; if left in, the resulting `.so` files require additional imports.
    - However, once built and loaded, the guest component complains that `import zlib` is not available (I suspect I need to enable that `componentize-py`'s `cpython` build.)
- `multidict` (loaded, untested)
    - This floats [a patch](https://github.com/aio-libs/multidict/pull/929) against the `master` branch of multidict to enable python 3.12 support. (3.11 doesn't require this patch, notably) 
- `pandas`
    - Patch out `npy_interrupt.h` in vendored `numpy` – ideally we'd thread `-DNPY_NO_SIGNAL` down through the `pandas` build but I wasn't able to figure out how to do so 😓
    - See note below about "Pandas and `__cxa_*`; pandas traps when loaded. 
- `sqlalchemy` (loaded, untested)
- `wrapt` (loaded, untested)
- `yaml` (loaded, untested)
- `yarl` (loaded, untested)

I've moved the `numpy/numpy` submodule to `numpy/src` and repeated that for all other packages.

---

## Pandas and `__cxa_*`

I have to use `wasm-merge` on `pandas/_libs/window/aggregations.cpython-311-wasm32-wasi.so` against a wasm module that stubs `__cxa_allocate_exception` and `__cxa_throw`. I'll move that operation into this PR if you're interested. The trap module looks like this:
```wast
;; its-a-trap.wat; a stub trap module
(module
  (func (export "__cxa_allocate_exception") (param i32) (result i32)
    (i32.const 0)
  )
  (func (export "__cxa_throw") (param i32 i32 i32)
    unreachable
  )
)
```

And the operation is, roughly,
```
wasm-tools parse wat/its-a-trap.wat > venv/its-a-trap.wasm
wasm-merge venv/its-a-trap.wasm env ./pandas/_libs/window/aggregations.cpython-311-wasm32-wasi.so base -o venv/merged.wasm
mv venv/merged.wasm ./pandas/_libs/window/aggregations.cpython-311-wasm32-wasi.so 
```

---

Again, thanks for the great work! I'm happy to make any changes you'd like to this PR, or we can keep the repos separate, whichever works best!

### CODE REVIEW

**Comment by dicej** [comment]
This is fantastic, @chrisdickinson!  Thanks so much.

I'll spend some time today looking this over and trying it out.

**Review by dicej — APPROVED** [review]
Looks great -- thanks.

I hit a slight hiccup trying to build on my Mac due to having GNU sed in my PATH instead of the BSD version, but once I corrected that it worked great.

A couple of ideas for follow ups (but no need to do anything in this PR):
- There's a lot of duplication among the build.sh scripts, so maybe we can factor out the common parts into a shared script
- I'd like to start publishing .whl files instead of .tar.gz files at some point.  There's no official WASI wheel naming convention yet, but perhaps we could make one up with input from e.g. @brettcannon and use that for the time being?

Anyway, awesome work!

**Comment by brettcannon** [comment]
Wheel tag naming is really going to depend on WASI-libc and maybe some code to `packaging`; I don't remember what the generic tag would look like. It requires installing `packaging` and looking at what `packaging.tags.sys_tags()` looks like under WASI (which I can eventually do, but I'm swamped w/ more pressing stuff ATM).

**Comment by brettcannon** [comment]
The default tag list is:
```
cp312-cp312-wasi_0_0_0_wasm32
cp312-abi3-wasi_0_0_0_wasm32
cp312-none-wasi_0_0_0_wasm32
cp311-abi3-wasi_0_0_0_wasm32
cp310-abi3-wasi_0_0_0_wasm32
cp39-abi3-wasi_0_0_0_wasm32
cp38-abi3-wasi_0_0_0_wasm32
cp37-abi3-wasi_0_0_0_wasm32
cp36-abi3-wasi_0_0_0_wasm32
cp35-abi3-wasi_0_0_0_wasm32
cp34-abi3-wasi_0_0_0_wasm32
cp33-abi3-wasi_0_0_0_wasm32
cp32-abi3-wasi_0_0_0_wasm32
py312-none-wasi_0_0_0_wasm32
py3-none-wasi_0_0_0_wasm32
py311-none-wasi_0_0_0_wasm32
py310-none-wasi_0_0_0_wasm32
py39-none-wasi_0_0_0_wasm32
py38-none-wasi_0_0_0_wasm32
py37-none-wasi_0_0_0_wasm32
py36-none-wasi_0_0_0_wasm32
py35-none-wasi_0_0_0_wasm32
py34-none-wasi_0_0_0_wasm32
py33-none-wasi_0_0_0_wasm32
py32-none-wasi_0_0_0_wasm32
py31-none-wasi_0_0_0_wasm32
py30-none-wasi_0_0_0_wasm32
cp312-none-any
py312-none-any
py3-none-any
py311-none-any
py310-none-any
py39-none-any
py38-none-any
py37-none-any
py36-none-any
py35-none-any
py34-none-any
py33-none-any
py32-none-any
py31-none-any
py30-none-any
```

The `wasi_0_0_0_wasm32` comes from [`sysconfig.get_platform()`](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_platform). I can get this to be customized once we are ready to figure out what platform compatibility is.

**Pull request merged**
